### PR TITLE
Added Documentation for Master Thesis of MarcGassenschmidt, regarding…

### PR DESCRIPTION
**Pull request by MarcGassenschmidt**
Added Documentation for Master Thesis of Marc Gassenschmidt. Architecture and Demo.

### CODE REVIEW

**Comment by vsimko** [comment]
Translate all texts to English first

**Comment by aklink** [comment]
~Conflict mkdocs.yml solved (keep master, ignore Pull request changes)~
~https://github.com/MarcGassenschmidt/biggis-docs merged into master~
Revert Commit c27d166c06c9704565d631911803236d17c47494
(because it is not translated into english yet)

**Comment by aklink** [comment]
see branch https://github.com/biggis-project/biggis-docs/tree/merge_stabilityofhotspots

**Comment by vsimko** [comment]
already merged manually

**Pull request closed without merging**
